
const jsonR =[`{
      "dia":"Segunda",
      "aula":{
      "N1":{
      "conteudo":"Clube",
      "hora-min":"730",
      "hora-max":"815"
      },
      "N2":{
      "conteudo":"Clube",
      "hora-min":"815",
      "hora-max":"900"
      },
      "N3":{
      "conteudo":"Prática experimental",
      "hora-min":"900",
      "hora-max":"945"
      },
      "N4":{
      "conteudo":"prática experimental",
      "hora-min":"1005",
      "hora-max":"1050"
      },
      "N5":{
      "conteudo":"artes",
      "hora-min":"1050",
      "hora-max":"1135"
      },
      "N6":{
      "conteudo":"artes",
      "hora-min":"1220",
      "hora-max":"1350"
      },
      "N7":{
      "conteudo":"matemática",
      "hora-min":"1350",
      "hora-max":"1435"
      },
      "N8":{
      "conteudo":"matemática",
      "hora-min":"1435",
      "hora-max":"1520"
      },
      "N9":{
      "conteudo":"Orientação de estudos",
      "hora-min":"1520",
      "hora-max":"1605"
      }
      }
  }`
  ,
  `{
     "dia":"terça",
     "aula":{
      "N1":{
      "conteudo":"Prática experimental",
      "hora-min":"730",
      "hora-max":"815"
      },
      "N2":{
      "conteudo":"Prática experimental",
      "hora-min":"815",
      "hora-max":"900"
      },
      "N3":{
      "conteudo":"Inglês",
      "hora-min":"900",
      "hora-max":"945"
      },
      "N4":{
      "conteudo":"Matemática",
      "hora-min":"1005",
      "hora-max":"1050"
      },
      "N5":{
      "conteudo":"Português",
      "hora-min":"1050",
      "hora-max":"1135"
      },
      "N6":{
      "conteudo":"Português",
      "hora-min":"1220",
      "hora-max":"1350"
      },
      "N7":{
      "conteudo":"Inglês",
      "hora-min":"1350",
      "hora-max":"1435"
      },
      "N8":{
      "conteudo":"Geografia",
      "hora-min":"1435",
      "hora-max":"1520"
      },
      "N9":{
      "conteudo":"Química",
      "hora-min":"1520",
      "hora-max":"1605"
      }
     }
  }`
  ,
  `{
     "dia":"quarta",
     "aula":{
      "N1":{
      "conteudo":"Física",
      "hora-min":"730",
      "hora-max":"815"
      },
      "N2":{
      "conteudo":"Sociologia",
      "hora-min":"815",
      "hora-max":"900"
      },
      "N3":{
      "conteudo":"Sociologia",
      "hora-min":"900",
      "hora-max":"945"
      },
      "N4":{
      "conteudo":"Projeto de vida",
      "hora-min":"1005",
      "hora-max":"1050"
      },
      "N5":{
      "conteudo":"Projeto de vida",
      "hora-min":"1050",
      "hora-max":"1135"
      },
      "N6":{
      "conteudo":"Física",
      "hora-min":"1220",
      "hora-max":"1350"
      },
      "N7":{
      "conteudo":"Nivelamento",
      "hora-min":"1350",
      "hora-max":"1435"
      },
      "N8":{
      "conteudo":"Nivelamento",
      "hora-min":"1435",
      "hora-max":"1520"
      },
      "N9":{
      "conteudo":"Geografia",
      "hora-min":"1520",
      "hora-max":"1605"
      }
     }
  }`
  ,
  `{
     "dia":"quinta",
     "aula":{
      "N1":{
      "conteudo":"Eletiva",
      "hora-min":"730",
      "hora-max":"815"
      },
      "N2":{
      "conteudo":"Eletiva",
      "hora-min":"815",
      "hora-max":"900"
      },
      "N3":{
      "conteudo":"Biologia",
      "hora-min":"900",
      "hora-max":"945"
      },
      "N4":{
      "conteudo":"Biologia",
      "hora-min":"1005",
      "hora-max":"1050"
      },
      "N5":{
      "conteudo":"Educação física",
      "hora-min":"1050",
      "hora-max":"1135"
      },
      "N6":{
      "conteudo":"Educação física",
      "hora-min":"1220",
      "hora-max":"1350"
      },
      "N7":{
      "conteudo":"Tecnologia e inovação",
      "hora-min":"1350",
      "hora-max":"1435"
      },
      "N8":{
      "conteudo":"Português",
      "hora-min":"1435",
      "hora-max":"1520"
      },
      "N9":{
      "conteudo":"Português",
      "hora-min":"1520",
      "hora-max":"1605"
      }
     }
  }`
  ,
  `{
     "dia":"sexta",
     "aula":{
      "N1":{
      "conteudo":"Filosofia",
      "hora-min":"730",
      "hora-max":"815"
      },
      "N2":{
      "conteudo":"Filosofia",
      "hora-min":"815",
      "hora-max":"900"
      },
      "N3":{
      "conteudo":"Matemática",
      "hora-min":"900",
      "hora-max":"945"
      },
      "N4":{
      "conteudo":"Matemática",
      "hora-min":"1005",
      "hora-max":"1050"
      },
      "N5":{
      "conteudo":"Prática experimental",
      "hora-min":"1050",
      "hora-max":"1135"
      },
      "N6":{
      "conteudo":"Química",
      "hora-min":"1220",
      "hora-max":"1350"
      },
      "N7":{
      "conteudo":"Português",
      "hora-min":"1350",
      "hora-max":"1435"
      },
      "N8":{
      "conteudo":"História",
      "hora-min":"1435",
      "hora-max":"1520"
      },
      "N9":{
      "conteudo":"História",
      "hora-min":"1520",
      "hora-max":"1605"
      }
     }
  }
  `
  ,
  `
  
  {
    "aula":{
  
    "intervalo":"Intervalo",
    "not":"Não a aula neste horário"
  }
  }
  
  `
  
  
  ];
  var json = jsonR;

